backend/python/src/masuda/masuda/urls.py
from django.contrib import admin
from django.urls import re_path, path
from django.conf.urls import include
from django.conf import settings
import debug_toolbar
from masudaapi.urls import router as masudaapi_router

urlpatterns = [
    re_path(r'^api/', include(masudaapi_router.urls)),
    path('web/', include('web.urls')),
    path('dummy/', include('dummy.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

backend/python/src/masuda/web/urls.py
from django.urls import path

from . import views
from .views import post_views, progress_views, graph_views

app_name = 'web'
urlpatterns = [
    path('', post_views.IndexView.as_view(), name='index'),
    path('<int:pk>/', post_views.DetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', post_views.delete, name='delete'),
    path('<int:pk>/space_masuda/', post_views.space_masuda, name='space_masuda'),
    path('selective_delete/', post_views.selective_delete, name='selective_delete'),
    path('fetch/', post_views.fetch, name='fetch'),
    path('<int:pk>/reload/', post_views.reload, name='reload'),
    path('<int:pk>/check/<int:checked>/', post_views.check_to_delete, name='check_to_delete'),
    path('to_be_deleted_later/', post_views.to_be_deleted_later, name='to_be_deleted_later'),
    path('uncheck_all/', post_views.uncheck_all, name='uncheck_all'),

    path('progress/', progress_views.IndexView.as_view(), name='progress.index'),
    path('progress/<int:pk>/stop/', progress_views.stop, name='progress.stop'),
    path('progress/<int:pk>/force_stop/', progress_views.force_stop, name='progress.force_stop'),
    path('progress/<int:pk>/delete/', progress_views.delete, name='progress.delete'),
    path('progress/<int:pk>/', progress_views.get, name='progress.get'),
    path('progress/filter_delete/', progress_views.filter_delete, name='progress.filter_delete'),

    path('graph/', graph_views.index, name='graph.index'),
]

backend/python/src/masuda/web/forms/post_forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from masudaapi.models import Post

class SearchForm(forms.Form):
    keyword = forms.CharField(
        label='キーワード',
        max_length=200,
        required=False
    )
    masuda_id = forms.CharField(
        label='増田ID',
        max_length=50,
        required=False
    )
    posted_at_from = forms.DateTimeField(
        label='投稿日時from',
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"}),
        input_formats=['%Y-%m-%d %H:%M'],
        required=False
    )
    posted_at_to = forms.DateTimeField(
        label='投稿日時to',
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"}),
        input_formats=['%Y-%m-%d %H:%M'],
        required=False
    )
    response_count_from = forms.IntegerField(
        label='トラックバック数from',
        required=False
    ) 
    response_count_to = forms.IntegerField(
        label='トラックバック数to',
        required=False
    ) 
    bookmark_count_from = forms.IntegerField(
        label='ブックマーク数from',
        required=False
    ) 
    bookmark_count_to = forms.IntegerField(
        label='ブックマーク数to',
        required=False
    ) 
    may_be_deleted = forms.BooleanField(
        label='削除されたかもしれない',
        required=False,
        widget=forms.CheckboxInput(
            # attrs={'class': 'form-control'}
        )
    )
    space_masuda = forms.BooleanField(
        label='スペース増田',
        required=False,
        widget=forms.CheckboxInput()
    )
    delete_later = forms.BooleanField(
        label='あとで消す',
        required=False,
        widget=forms.CheckboxInput(
            # attrs={'class': 'form-control'}
        )
    )
    page_size = forms.IntegerField(
        label='ページあたりの件数',
        initial=25,
        required=False,
        min_value=1,
        validators=[MinValueValidator(1)]
    )

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body')

class FetchForm(forms.Form):
    page_from = forms.IntegerField(
        label='ページ数from',
        initial=1,
        required=True,
        min_value=1,
        validators=[MinValueValidator(1)]
    )
    page_to = forms.IntegerField(
        label='ページ数to',
        initial=1,
        required=True,
        min_value=1,
        validators=[MinValueValidator(1)]
    )

class SelectiveDeleteForm(forms.Form):

    class AcceptAnythingMultipleChoiceField(forms.MultipleChoiceField):
        def validate(self, value):
            if self.required and not value:
                raise ValidationError(
                    self.error_messages['required'], 
                    code='required'
                )
    del_ids = AcceptAnythingMultipleChoiceField(
        required=True,
        # choices=(('1', 'a'), ('2', 'b')),
        # widget=forms.CheckboxSelectMultiple
    )

backend/python/src/masuda/web/views/post_views.py
from ast import Delete
from this import d
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.views import generic
from django.views.decorators.http import require_http_methods
from django.core import management
from django.contrib import messages
from django.db.models import Q, FilteredRelation
from django.conf import settings 

import re
import time
import datetime
import json
import subprocess
import logging

from masuda import const
from masudaapi.models import Post, HatenaUser, Progress, StopCommand, Delete_Post, Delete_Later_Check
from masudaapi.lib import user_getter
from web.forms.post_forms import PostForm, SearchForm, FetchForm, SelectiveDeleteForm

class IndexView(generic.ListView):
    model = Post
    template_name = 'web/post/index.html'
    context_object_name = 'post_list'
    paginate_by = const.HATENA['PAGE_SIZE']
    ordering = '-posted_at'

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)

        user = user_getter.get()
        queryset = queryset.filter(user=user)

        input = SearchForm(self.request.GET)
        if input.is_valid():
            keyword = input.cleaned_data.get('keyword')
            masuda_id = input.cleaned_data.get('masuda_id')
            bookmark_count_from = input.cleaned_data.get('bookmark_count_from')
            bookmark_count_to = input.cleaned_data.get('bookmark_count_to')
            response_count_from = input.cleaned_data.get('response_count_from')
            response_count_to = input.cleaned_data.get('response_count_to')
            posted_at_from = input.cleaned_data.get('posted_at_from')
            posted_at_to = input.cleaned_data.get('posted_at_to')
            may_be_deleted = input.cleaned_data.get('may_be_deleted')
            page_size = input.cleaned_data.get('page_size')
            space_masuda = input.cleaned_data.get('space_masuda')
            delete_later = input.cleaned_data.get('delete_later')

            if space_masuda:
                queryset = queryset.filter(title='', body=' ')
            elif keyword:
                keywords = re.split(' |　', keyword)
                for kw in keywords:
                    queryset = queryset.filter(Q(title__icontains=kw)|Q(body__icontains=kw))
            if masuda_id:
                queryset = queryset.filter(masuda_id=masuda_id)
            if bookmark_count_from is not None:
                queryset = queryset.filter(bookmark_count__gte=bookmark_count_from)
            if bookmark_count_to is not None:
                queryset = queryset.filter(bookmark_count__lte=bookmark_count_to)
            if response_count_from is not None:
                queryset = queryset.filter(response_count__gte=response_count_from)
            if response_count_to is not None:
                queryset = queryset.filter(response_count__lte=response_count_to)
            if posted_at_from:
                queryset = queryset.filter(posted_at__gte=posted_at_from)
            if posted_at_to:
                queryset = queryset.filter(posted_at__lte=posted_at_to)
            if page_size:
                self.paginate_by = page_size
            if may_be_deleted:
                queryset = queryset.filter(may_be_deleted=may_be_deleted)
            if delete_later:
                queryset = queryset.filter(delete_later_check__isnull=False, delete_later_check__checked=True)

        order_by = '-posted_at'
        sort_desc = self.request.GET.get('sort_desc')
        sort_asc = self.request.GET.get('sort_asc')
        if sort_desc in ['id', 'response_count', 'bookmark_count', 'posted_at']:
            order_by = '-' + sort_desc
        elif sort_asc in ['id', 'response_count', 'bookmark_count', 'posted_at']:
            order_by = sort_asc

        if sort_desc in ['posted_at', 'id'] or sort_asc in ['posted_at', 'id']:
            queryset = queryset.order_by(order_by)
        else:
            queryset = queryset.order_by(order_by, '-posted_at')
        queryset = queryset.select_related('delete_later_check')
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['form'] = SearchForm(self.request.GET or None)
        context['fetch_form'] = FetchForm(self.request.GET or None)
        context['parameters'] = ''
        context['sort_directions'] = {'id': 'desc', 'posted_at': 'desc', 'bookmark_count': 'desc', 'response_count': 'desc'}
        context['sort_parameter'] = ''
        get_copy = self.request.GET.copy()
        sort_desc = get_copy.pop('sort_desc', ['']).pop()
        sort_asc = get_copy.pop('sort_asc', ['']).pop()
        parameters = get_copy.pop('page', True) and get_copy.urlencode()
        if parameters:
            context['parameters'] = '&' + parameters
        if sort_desc:
            context['sort_parameter'] = '&sort_desc=' + sort_desc
            if sort_desc in context['sort_directions'].keys():
                context['sort_directions'][sort_desc] = 'asc'
        if sort_asc:
            context['sort_parameter'] = '&sort_asc=' + sort_asc
            if sort_asc in context['sort_directions'].keys():
                context['sort_directions'][sort_asc] = 'desc'

        context['anond_url'] = const.HATENA['ANOND_URL']
        context['del_form'] = SelectiveDeleteForm(None)
        context['abbr_length'] = const.ABBREVIATION_LENGTH
        context['use_space_masuda'] = const.USE_SPACE_MASUDA
        
        return context

class DetailView(generic.DetailView):
    model = Post
    template_name = 'web/post/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['anond_url'] = const.HATENA['ANOND_URL']
        return context

def delete(request, pk):
    user = user_getter.get()
    post = get_object_or_404(Post, pk=pk, user=user)
    params = {}
    if post.may_be_deleted:
        post.delete()
        params['result'] = 'success'
        params['message'] = f'Deleted id:{pk}({post.masuda_id} may have been deleted)'
        json_str = json.dumps(params, ensure_ascii=False, indent=2)
        return HttpResponse(json_str)

    # result = management.call_command('delete-masuda', post.id)
    try:
        process = subprocess.run(["python", 'manage.py', 'delete-masuda', str(post.id)], check=True, capture_output=True)
        if re.search(r'success', process.stdout.decode()):
            params['result'] = 'success'
            params['message'] = f'Deleted id:{pk}({post.masuda_id})'
        else:
            params['result'] = 'failure'
            params['message'] = f'Failed to delete id:{pk}({post.masuda_id})'
    except subprocess.CalledProcessError as e:
        params['result'] = 'failure'
        params['message'] = f'Failed to delete id:{pk}({post.masuda_id})'

    json_str = json.dumps(params, ensure_ascii=False, indent=2)
    return HttpResponse(json_str)

def space_masuda(request, pk):
    user = user_getter.get()
    post = get_object_or_404(Post, pk=pk, user=user)
    params = {}
    # result = management.call_command('empty-masuda', post.id)
    try:
        process = subprocess.run(["python", 'manage.py', 'empty-masuda', str(post.id)], check=True, capture_output=True)
        if re.search(r'success', process.stdout.decode()):
            params['result'] = 'success'
            params['message'] = f'Emptied id:{pk}({post.masuda_id})'
        else:
            params['result'] = 'failure'
            params['message'] = f'Failed to empty id:{pk}({post.masuda_id})'
    except subprocess.CalledProcessError as e:
        params['result'] = 'failure'
        params['message'] = f'Failed to empty id:{pk}({post.masuda_id})'

    json_str = json.dumps(params, ensure_ascii=False, indent=2)
    return HttpResponse(json_str)

def reload(request, pk):
    user = user_getter.get()
    post = get_object_or_404(Post, pk=pk, user=user)
    params = {}
    abbr_length = const.ABBREVIATION_LENGTH
    # result = management.call_command('empty-masuda', post.id)
    try:
        process = subprocess.run(["python", 'manage.py', 'reload-masuda', str(post.id)], check=True, capture_output=True)
        if re.search(r'success', process.stdout.decode()):
            params['result'] = 'success'
            params['message'] = f'Reloaded id:{pk}({post.masuda_id})'
            post = Post.objects.filter(id=pk).first()
            params['title'] = post.title[0:abbr_length - 1] + ('...' if len(post.title) > abbr_length else '')
            params['body'] = post.body[0:abbr_length - 1] + ('...' if len(post.body) > abbr_length else '')
            params['response_count'] = post.response_count
            params['bookmark_count'] = post.bookmark_count
        else:
            params['result'] = 'failure'
            params['message'] = f'Failed to reload id:{pk}({post.masuda_id})'
    except subprocess.CalledProcessError as e:
        params['result'] = 'failure'
        params['message'] = f'Failed to reload id:{pk}({post.masuda_id})'

    json_str = json.dumps(params, ensure_ascii=False, indent=2)
    return HttpResponse(json_str)

def selective_delete(request):
    params = {}
    user = user_getter.get()
    # result = management.call_command('selective-delete-masuda')

    checks = Delete_Later_Check.objects.filter(post__user=user)
    if checks.count() == 0:
        params['result'] = 'failure'
        params['message'] = 'No posts to be deleted.'
        json_str = json.dumps(params, ensure_ascii=False, indent=2)
        return HttpResponse(json_str)

    progress = Progress.objects.create(
        user = user,
        total = 0,
        processed = 0,
        action = Progress.ACTIONS.DELETE,
        overview = '',
        status = Progress.STATUS.PENDING
    )
    subprocess.Popen(["python", 'manage.py', 'selective-delete-masuda', '--progress', str(progress.id)])

backend/python/src/masuda/web/templates/web/post/detail.html
{% extends "web/layouts/base.html" %}
{% block content %}
<div class="container">
    <h4 class="">{{ post.title }}</h4>
    <div class="row">
        <div class="col">{{ post.posted_at }}</div>
    </div>
    <div class="row mt-3 mb-3">
        <div class="col">{{ post.body|linebreaksbr }}</div>
    </div>
    <div class="row">
        <div class="col">ブックマーク: {{ post.bookmark_count }}</div>
    </div>
    <div class="row">
        <div class="col">トラックバック: {{ post.response_count }}</div>
    </div>
    <div class="row">
        <div class="col">増田ID: <a href="{{ anond_url }}/{{ post.masuda_id }}">{{ post.masuda_id }}</a></div>
    </div>
    <a href="{% url 'web:index' %}" class="btn btn-secondary">back</a>
</div>
{% endblock %}

backend/python/src/masuda/web/templates/web/post/index.html
{% extends "web/layouts/base.html" %}
{% block title %}Posts - {{ block.super }}{% endblock  %}
{% block content %}
{% load static widget_tweaks %}
<div class="container">
    {% if messages %}
	<ul class="messages_ul">
		{% for message in messages %}
			<li class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">{{ message }}</li>
		{% endfor %}
	</ul>
    {% endif %}
    
    <h3>取込</h3>
    <div class="row">
        <div class="col mb-4">
            <form action="{% url 'web:fetch' %}" method="post" id="fetch-form" class="mb-3">
                {% csrf_token %}
                {{ fetch_form.page_from.label_tag }}
                {{ fetch_form.page_from | add_class:'form-control' }}
                {{ fetch_form.page_to.label_tag }}
                {{ fetch_form.page_to | add_class:'form-control'  }}
                <button class="btn btn-primary mt-1" id="fetch-btn">取込</button>
            </form>
        </div>
    </div>

    <h3>検索</h3>
    <div class="row mb-4">
        <div class="col">
            <form method="GET" action="">
                <div class="row mb-3">
                    <div class="col">
                        {{ form.keyword.label_tag }}
                        {{ form.keyword | add_class:'form-control' }}
                        {{ form.keyword.errors }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        {{ form.masuda_id.label_tag }}
                        {{ form.masuda_id | add_class:'form-control' }}
                        {{ form.masuda_id.errors }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        {{ form.posted_at_from.label_tag }}
                        {{ form.posted_at_from | add_class:'form-control' }}
                        {{ form.posted_at_from.errors }}
                    </div>
                    <div class="col">
                        {{ form.posted_at_to.label_tag }}
                        {{ form.posted_at_to | add_class:'form-control' }}
                        {{ form.posted_at_to.errors }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        {{ form.bookmark_count_from.label_tag }}
                        {{ form.bookmark_count_from | add_class:'form-control' }}
                        {{ form.bookmark_count_from.errors }}
                    </div>
                    <div class="col">
                        {{ form.bookmark_count_to.label_tag }}
                        {{ form.bookmark_count_to | add_class:'form-control' }}
                        {{ form.bookmark_count_to.errors }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        {{ form.response_count_from.label_tag }}
                        {{ form.response_count_from | add_class:'form-control' }}
                        {{ form.response_count_from.errors }}
                    </div>
                    <div class="col">
                        {{ form.response_count_to.label_tag }}
                        {{ form.response_count_to | add_class:'form-control' }}
                        {{ form.response_count_to.errors }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        {{ form.page_size.label_tag }}
                        {{ form.page_size | add_class:'form-control' }}
                        {{ form.page_size.errors }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        {{ form.delete_later.label_tag }}
                        {{ form.delete_later }}
                        {{ form.delete_later.errors }}
                    </div>
                    <div class="col">
                        {{ form.may_be_deleted.label_tag }}
                        {{ form.may_be_deleted }}
                        {{ form.may_be_deleted.errors }}
                    </div>
                    <div class="col">
                        {% if use_space_masuda %}
                        {{ form.space_masuda.label_tag }}
                        {{ form.space_masuda }}
                        {{ form.space_masuda.errors }}
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-primary">検索</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
    <h3>一覧</h3>
    {% if post_list %}
        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteLaterModal">「あとで消す」記事をついに消す</button>
        <button class="btn btn-secondary" id="uncheck-all-btn">「あとで消す」選択全解除</button>
        <table class="table table-striped">
            <tr>
                <th>あとで消す</th>
                <th>
                    <a href="{% url 'web:index' %}?sort_{{ sort_directions.id }}=id{{ parameters }}">ID</a>
                </th>
                <th>増田ID</th>
                <th>タイトル</th>
                <th>本文</th>
                <th><a href="{% url 'web:index' %}?sort_{{ sort_directions.posted_at }}=posted_at{{ parameters }}">投稿日時</a></th>
                <th><a href="{% url 'web:index' %}?sort_{{ sort_directions.bookmark_count }}=bookmark_count{{ parameters }}">B</a></th>
                <th><a href="{% url 'web:index' %}?sort_{{ sort_directions.response_count }}=response_count{{ parameters }}">TB</a></th>
                <th style="width:15%">操作</th>
            </tr>
            {% for post in post_list %}
            <tr id="row-{{ post.id }}">
                <td>
                    <label class="ps-1 pe-1 pb-5" style="display:block;" for="del_ids-{{ post.id }}">
                        <input type="checkbox" name="del_ids" class="del_ids" id="del_ids-{{ post.id }}" value="{{ post.id }}" {% if post.delete_later_check %}checked{% endif %}/>&nbsp;
                    </label>
                </td>
                <td>{{ post.id }}</td>
                <td>
                    <a href="{{ anond_url }}/{{ post.masuda_id }}" target="_blank">
                        {{ post.masuda_id }}
                    </a>
                    {% if post.may_be_deleted %}
                    <p class="text-danger">削除済？</p>
                    {% endif %}
                </td>
                <td class="title">{{ post.title | truncatechars:abbr_length  }}</td>
                <td class="body">{{ post.body | truncatechars:abbr_length }}</td>
                <td>{{ post.posted_at }}</td>
                <td class="bookmark_count">{{ post.bookmark_count }}</td>
                <td class="response_count">{{ post.response_count }}</td>
                <td>
                    <div class="d-grid gap-2 d-md-block">
                        <a class="btn btn-primary btn-sm mb-2" href="{% url 'web:detail' post.id %}">詳細</a>
                        <button class="btn btn-primary btn-sm mb-2 reload-btn" data-id="{{ post.id }}" data-url="{% url 'web:reload' post.id %}">再読込</button>
                        <button class="btn btn-danger btn-sm mb-2 del-btn" data-id="{{ post.id }}" data-url="{% url 'web:delete' post.id %}">削除</button>
                        {% if use_space_masuda %}
                        <button title="space masuda" class="btn btn-secondary btn-sm mb-2 space-masuda-btn" data-id="{{ post.id }}" data-url="{% url 'web:space_masuda' post.id %}">space masuda</a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% endfor %}
        </table>

        {% include 'web/layouts/pager.html' %}
    {% else %}
        <p>No posts are available.</p>
    {% endif %}
</div>

  
<form action="" method="post" id="ud-form" class="d-none">
    {% csrf_token %}
</form>

<form action="{% url 'web:selective_delete' %}" method="post" id="selective-delete-form" class="d-none">
    {% csrf_token %}
</form>

<form action="{% url 'web:uncheck_all' %}" method="post" id="uncheck-all-form" class="d-none">
    {% csrf_token %}
</form>

<form action="{% url 'web:index' %}" method="post" id="check-form" class="d-none">
    {% csrf_token %}
</form>

<button class="btn btn-primary position-relative position-fixed bottom-0 end-0 me-3" type="button" id="info-btn" data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom">
<!-- <button type="button" class="btn btn-primary position-relative position-fixed bottom-0 end-0"> -->
    Info
    <span class="position-absolute top-0 start-100 translate-middle badge border border-light rounded-circle bg-danger p-2 d-none" id="info-badge"><span class="visually-hidden">unread messages</span></span>
</button>

<!-- offcanvas -->
<div class="offcanvas offcanvas-bottom" tabindex="-1" id="offcanvasBottom" aria-labelledby="offcanvasBottomLabel" data-bs-scroll="true" data-bs-backdrop="false" >
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasBottomLabel">Info</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body small" id="info-area"></div>
</div>

<!-- alert skeleton -->
<div class="alert alert-success alert-dismissible fade show d-none" role="alert" id="as-skeleton">
    <span></span>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<div class="alert alert-danger alert-dismissible fade show d-none" role="alert" id="ad-skeleton">
    <span></span>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<div class="alert alert-light alert-dismissible fade show d-none" role="alert" id="ap-skeleton" data-url="{% url 'web:progress.index' %}">
    <span class="overview"></span>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
    </div>
    <div class="message"></div>
</div>

<!-- modal -->
<div class="modal fade" id="deleteLaterModal" tabindex="-1" aria-labelledby="deleteLaterModalLabel" aria-hidden="true" data-url="{% url 'web:to_be_deleted_later' %}" data-anond-url="{{ anond_url }}">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">以下の記事を削除します</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
          <button type="button" class="btn btn-primary" id="deleteLaterModalExecute" data-bs-dismiss="modal">削除</button>
        </div>
      </div>
    </div>
</div>
<script>

</script>
{% endblock %}
{% block js %}
<script src="{% static 'web/js/post/index.js' %}" type="module"></script>
{% endblock %}